# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockerizedapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://usecase11.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ed90029f0a284bb7879ca28414aca434 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cc3f9ee7c7274fa4a326c62547404da7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: usecase11.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed90029f0a284bb7879ca28414aca434 }}/back2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockerizedapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bf8d2498201c46aaadb7bd350cd2cc38 }}
        images: 'usecase11.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed90029f0a284bb7879ca28414aca434 }}/back2:${{ github.sha }}'